# Build Rust code
name: Build Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Update local toolchain
      run: |
        rustup update

    - name: Toolchain info
      run: |
        cargo --version --verbose
        rustc --version

    - name: Test
      run: |
        cargo check
        cargo test --all          

    - name: Build
      run: |
        cargo build --release  
